SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[IdentityProvider](
	[Id] [bigint] IDENTITY(1,1) NOT NULL,
	[APIKeyId] [bigint] NOT NULL,
	[EntryPoint] [varchar](1023) NOT NULL,
	[Name] [nvarchar](50) NOT NULL,
 CONSTRAINT [PK_IdentityProvider] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[IdentityProvider]  WITH CHECK ADD  CONSTRAINT [FK_IdentityProvider_APIKey] FOREIGN KEY([APIKeyId])
REFERENCES [dbo].[APIKey] ([Id])
GO
ALTER TABLE [dbo].[IdentityProvider] CHECK CONSTRAINT [FK_IdentityProvider_APIKey]
GO
