

ALTER DATABASE NewData SET RECOVERY SIMPLE WITH NO_WAIT
GO
ALTER DATABASE NewData SET RECOVERY SIMPLE 
GO
USE NewData 
GO
DBCC SHRINKFILE (N'SizeUpData_log' , 1, TRUNCATEONLY)
GO


ALTER DATABASE NewData SET RECOVERY FULL WITH NO_WAIT
GO
ALTER DATABASE NewData SET RECOVERY FULL 
GO

