USE [master]
GO

-- The following may be handy if you need to rename a previous --
-- database, and you can't get an exclusive database lock.     --
-- alter database NewData set single_user with rollback immediate
-- alter database NewData modify name = [NewData.1]
-- alter database [NewData.1] set multi_user
-- go

/****** Object:  Database [NewData]    Script Date: 1/25/2018 2:16:27 PM ******/
CREATE DATABASE [NewData] ON  PRIMARY 
( NAME = N'SizeUpData', FILENAME = N'F:\NewData.mdf' , SIZE = 949131904KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'SizeUpData_log', FILENAME = N'D:\NewData.ldf' , SIZE = 658058688KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [NewData] SET COMPATIBILITY_LEVEL = 100
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [NewData].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [NewData] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [NewData] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [NewData] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [NewData] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [NewData] SET ARITHABORT OFF 
GO

ALTER DATABASE [NewData] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [NewData] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [NewData] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [NewData] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [NewData] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [NewData] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [NewData] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [NewData] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [NewData] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [NewData] SET  DISABLE_BROKER 
GO

ALTER DATABASE [NewData] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [NewData] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [NewData] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [NewData] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [NewData] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [NewData] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [NewData] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [NewData] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [NewData] SET  MULTI_USER 
GO

ALTER DATABASE [NewData] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [NewData] SET DB_CHAINING OFF 
GO

ALTER DATABASE [NewData] SET  READ_WRITE 
GO

